const state={page:'capture',ideas:[],tasks:[],schedules:[],topics:[]};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>new Date().toLocaleDateString('en-CA');
const dateText=v=>v?new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'short',day:'numeric'}).format(new Date(v+'T00:00:00')):'';
const dateTimeText=v=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v));
const statusName=s=>({New:'新想法',Thinking:'思考中',Ready:'准备实践',Implemented:'已实现',Shelved:'搁置',Todo:'Todo',Doing:'Doing',Done:'Done'})[s]||s;

async function refresh(){[state.ideas,state.tasks,state.schedules,state.topics]=await Promise.all([window.its.list('idea'),window.its.list('task'),window.its.list('schedule'),window.its.listTopics()])}
function toast(m,error=false){const e=$('#toast');e.textContent=m;e.className=(error?'error ':'')+'show';setTimeout(()=>e.className='',2200)}
function tags(i){return(i.topics||[]).map(t=>`<span class="pill"># ${esc(t.name)}</span>`).join('')}
function empty(a,b){return`<div class="empty card"><b>${a}</b>${b}</div>`}
function shell(k,t,s,a=''){return`<div class="page"><header class="page-head"><div><div class="eyebrow">${k}</div><h1>${t}</h1><p class="subtitle">${s}</p></div>${a}</header><div id="content"></div></div>`}

function renderCapture(){
  $('#app').innerHTML=`<div class="page"><div class="eyebrow">QUICK CAPTURE</div><h1>刚刚想到了什么？</h1><p class="subtitle">先记下来，整理可以留给以后。</p><section class="capture-card card"><textarea id="capture-text" autofocus placeholder="写下你的想法……\n\n支持多段文字和换行。"></textarea><div class="actions"><button class="primary" id="capture-save">保存 Idea</button></div></section><p class="hint"><kbd>Ctrl</kbd> + <kbd>Enter</kbd> 快速保存</p></div>`;
  const save=async()=>{const content=$('#capture-text').value;if(!content.trim())return toast('先写下一点内容吧',true);try{await window.its.save('idea',{content,status:'New',topic_ids:[]});$('#capture-text').value='';await refresh();toast('Idea 已保存')}catch(e){toast(e.message,true)}};
  $('#capture-save').onclick=save;$('#capture-text').onkeydown=e=>{if(e.ctrlKey&&e.key==='Enter')save()};
}
function renderIdeas(){
  $('#app').innerHTML=shell('IDEAS','灵感',`${state.ideas.length} 条想法`,'<button class="primary" data-new="idea">＋ 新建 Idea</button>');
  $('#content').innerHTML=state.ideas.length?`<div class="list">${state.ideas.map(i=>`<article class="item card"><div class="item-main"><div class="item-title">${esc(i.content)}</div><div class="meta"><span class="pill status">${statusName(i.status)}</span>${tags(i)}<span>${dateTimeText(i.created_at)}</span></div></div>${itemActions('idea',i.id)}</article>`).join('')}</div>`:empty('还没有灵感','从「记录」页快速写下第一个想法。')
}
function itemActions(t,id){return`<div class="item-actions"><button class="icon-btn" data-edit="${t}" data-id="${id}">编辑</button><button class="icon-btn danger" data-remove="${t}" data-id="${id}">删除</button></div>`}
function renderTasks(){
  const active=state.tasks.filter(t=>t.status!=='Done');$('#app').innerHTML=shell('TODO','待办事项',`${active.length} 项未完成`,'<button class="primary" data-new="task">＋ 新建 Task</button>');
  $('#content').innerHTML=state.tasks.length?`<div class="list">${state.tasks.map(t=>`<article class="item card"><button class="check ${t.status==='Done'?'done':''}" data-toggle="${t.id}">${t.status==='Done'?'✓':''}</button><div class="item-main"><div class="item-title" ${t.status==='Done'?'style="text-decoration:line-through;opacity:.55"':''}>${esc(t.title)}</div>${t.description?`<div class="item-desc">${esc(t.description)}</div>`:''}<div class="meta"><span class="pill status">${statusName(t.status)}</span>${t.deadline?`<span class="pill ${t.deadline<today()&&t.status!=='Done'?'overdue':''}">DDL ${dateText(t.deadline)}</span>`:'<span>No Deadline</span>'}${tags(t)}</div></div>${itemActions('task',t.id)}</article>`).join('')}</div>`:empty('Todo 是空的','创建一件需要完成的事情，DDL 可以留空。')
}
function renderSchedules(){
  const upcoming=state.schedules.filter(s=>s.date>=today());$('#app').innerHTML=shell('SCHEDULE','日程',`今日与未来共 ${upcoming.length} 项`,'<button class="primary" data-new="schedule">＋ 新建 Schedule</button>');
  if(!upcoming.length){$('#content').innerHTML=empty('近期没有安排','创建一个有明确日期的日程。');return}let last='';$('#content').innerHTML=upcoming.map(s=>{const head=s.date!==last?`<div class="date-group">${s.date===today()?'今天 · ':''}${dateText(s.date)}</div>`:'';last=s.date;return`${head}<article class="item card"><div class="item-main"><div class="item-title">${esc(s.title)}</div>${s.description?`<div class="item-desc">${esc(s.description)}</div>`:''}<div class="meta"><span class="pill status">${s.start_time?`${s.start_time}${s.end_time?' – '+s.end_time:''}`:'全天'}</span>${tags(s)}</div></div>${itemActions('schedule',s.id)}</article>`}).join('')
}
function renderTopics(){
  $('#app').innerHTML=shell('TOPICS','主题','跨越灵感、任务与日程的聚合视图','<button class="primary" data-new-topic>＋ 新建 Topic</button>');$('#content').innerHTML=state.topics.length?`<div class="topic-grid">${state.topics.map(t=>`<article class="topic-card card"><button data-topic="${t.id}"><h2># ${esc(t.name)}</h2><p>${esc(t.description||'暂无描述')}</p><span class="pill">${t.item_count} 项内容</span></button></article>`).join('')}</div><div id="topic-detail"></div>`:empty('还没有 Topic','创建主题，把相关内容聚在一起。')
}
function topicOptions(selected=[]){return state.topics.map(t=>`<label><input type="checkbox" name="topics" value="${t.id}" ${selected.includes(t.id)?'checked':''}> # ${esc(t.name)}</label>`).join('')||'<span class="subtitle">可先在 Topic 页面创建主题</span>'}
function openEntityModal(type,item={}){
  const selected=(item.topics||[]).map(t=>t.id),idea=type==='idea',task=type==='task';
  document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop"><form class="modal card"><div class="modal-head"><h2>${item.id?'编辑':'新建'} ${idea?'Idea':task?'Task':'Schedule'}</h2><button type="button" data-close>×</button></div>${idea?`<div class="field"><label>内容</label><textarea name="content" required>${esc(item.content||'')}</textarea></div><div class="field"><label>状态</label><select name="status">${['New','Thinking','Ready','Implemented','Shelved'].map(s=>`<option ${item.status===s?'selected':''} value="${s}">${statusName(s)}</option>`).join('')}</select></div>`:`<div class="field"><label>标题</label><input name="title" required value="${esc(item.title||'')}"></div><div class="field"><label>描述</label><textarea name="description">${esc(item.description||'')}</textarea></div>${task?`<div class="row"><div class="field"><label>状态</label><select name="status">${['Todo','Doing','Done'].map(s=>`<option ${item.status===s?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>DDL（可选）</label><input type="date" name="deadline" value="${item.deadline||''}"></div></div>`:`<div class="field"><label>日期</label><input type="date" name="date" required value="${item.date||today()}"></div><div class="row"><div class="field"><label>开始时间（可选）</label><input type="time" name="start_time" value="${item.start_time||''}"></div><div class="field"><label>结束时间（可选）</label><input type="time" name="end_time" value="${item.end_time||''}"></div></div>`}`}<div class="field"><label>Topic（可选）</label><div class="topic-checks">${topicOptions(selected)}</div></div><div class="actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">保存</button></div></form></div>`);
  const modal=$('.modal-backdrop');$$('[data-close]',modal).forEach(b=>b.onclick=()=>modal.remove());$('form',modal).onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id=item.id;data.topic_ids=$$('input[name=topics]:checked',modal).map(x=>x.value);try{await window.its.save(type,data);modal.remove();await refresh();render();toast('已保存')}catch(err){toast(err.message,true)}}
}
function openTopicModal(){
  document.body.insertAdjacentHTML('beforeend','<div class="modal-backdrop"><form class="modal card"><div class="modal-head"><h2>新建 Topic</h2><button type="button" data-close>×</button></div><div class="field"><label>名称</label><input name="name" required autofocus></div><div class="field"><label>描述</label><textarea name="description"></textarea></div><div class="actions"><button type="button" class="secondary" data-close>取消</button><button class="primary">保存</button></div></form></div>');const modal=$('.modal-backdrop');$$('[data-close]',modal).forEach(b=>b.onclick=()=>modal.remove());$('form',modal).onsubmit=async e=>{e.preventDefault();try{await window.its.saveTopic(Object.fromEntries(new FormData(e.target)));modal.remove();await refresh();render();toast('Topic 已创建')}catch(err){toast(err.message,true)}}
}
async function showTopic(id){const t=await window.its.topicDetail(id);const section=(title,items,type)=>`<section class="topic-section"><h2>${title} · ${items.length}</h2>${items.length?`<div class="list">${items.map(x=>`<article class="item card"><div class="item-title">${esc(type==='idea'?x.content:x.title)}</div></article>`).join('')}</div>`:'<p class="subtitle">暂无内容</p>'}</section>`;$('#topic-detail').innerHTML=`<div class="topic-detail"><div class="eyebrow">TOPIC DETAIL</div><h1># ${esc(t.name)}</h1><p class="subtitle">${esc(t.description||'')}</p>${section('Ideas',t.ideas,'idea')}${section('Tasks',t.tasks,'task')}${section('Schedules',t.schedules,'schedule')}</div>`;$('#topic-detail').scrollIntoView({behavior:'smooth'})}
function bindCommon(){
  $$('[data-new]').forEach(b=>b.onclick=()=>openEntityModal(b.dataset.new));$$('[data-edit]').forEach(b=>b.onclick=()=>openEntityModal(b.dataset.edit,state[b.dataset.edit+'s'].find(x=>x.id===b.dataset.id)));$$('[data-remove]').forEach(b=>b.onclick=async()=>{if(!confirm('确定删除这条内容？数据会以 soft delete 方式保留。'))return;await window.its.remove(b.dataset.remove,b.dataset.id);await refresh();render();toast('已删除')});$$('[data-toggle]').forEach(b=>b.onclick=async()=>{const t=state.tasks.find(x=>x.id===b.dataset.toggle);await window.its.save('task',{...t,status:t.status==='Done'?'Todo':'Done',topic_ids:t.topics.map(x=>x.id)});await refresh();render()});$('[data-new-topic]')?.addEventListener('click',openTopicModal);$$('[data-topic]').forEach(b=>b.onclick=()=>showTopic(b.dataset.topic))
}
function render(){({capture:renderCapture,ideas:renderIdeas,tasks:renderTasks,schedules:renderSchedules,topics:renderTopics})[state.page]();$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));bindCommon()}
$$('nav button').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render()});refresh().then(render).catch(e=>toast('启动失败：'+e.message,true));
